main: CI

on:
#События, которые запускают
push:
branches: [ "main™ ]

pull_requet:
branches: [ “main” ]


jobs:

ny build_job:

runs-on: ubuntu-latest
step:

- uses: actions/checkout@v3

- name: npm install, test and build
run: |
npm install
npm run build

- name: Run a one-line script
run: echo Hello, world!


- name: Run a multi-line script
run: |
echo Add other actions to build,
echo test, and deploy your project.

- name: Run JS file for test
run: node js/script.js
